refactor: improve antiaim documentation
neverlosecc/api-documentation pull request #41
Opened 2021-05-19 15:53 UTC by Le0Developer

- Add info box that Override* functions can only be used during the `prediction` callback (maybe better wording?)
- Add value ranges
- Add example values which make (more) sense
- Change type from float to int

2021-05-19 19:53 UTC, es3n1n requested changes

2021-05-19 19:53 UTC, es3n1n commented on developers/tables/antiaim.md
> +Override* functions must be called during the [prediction](../other/callbacks.md) callbacks.
override functions can be called only from pre-createmove callbacks (`pre_prediction`, `prediction`)

2021-05-20 18:56 UTC, es3n1n requested changes

2021-05-20 18:56 UTC, es3n1n commented on developers/tables/antiaim.md
> +| value | int | A new desync limit value (0 - 58) |
this value can be float as well 🤔

2021-05-20 18:57 UTC, es3n1n commented on developers/tables/antiaim.md
> +| value | int | A new desync limit value (0 - 58) |
i mean, every value of override* functions can be float as well

2021-05-21 17:12 UTC, Le0Developer commented on developers/tables/antiaim.md
> +| value | int | A new desync limit value (0 - 58) |
Whoops. Must've done 2 changes to fix an issue in my script and thought that that was the cause.  
Just rechecked and it indeed accepts and works with floats.

2021-05-21 17:20 UTC, es3n1n approved these changes
Thanks

2021-05-21 17:21 UTC, merged